"""
Generate per-category wordlists by intersecting hand-curated seed lists with
the project's dictionary. Output: backend/app/data/category_words/<id>.txt
(one word per line, uppercase).

Run once on setup, then again whenever you tweak SEEDS or the dictionary.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "backend" / "app" / "data"
DICT_PATH = DATA / "dictionary.txt"
OUT_DIR = DATA / "category_words"

# Hand-curated seed lists — intentionally generous so intersect-with-dictionary
# yields a usable set per category. Words are case-insensitive; multi-word
# entries are skipped (game uses single-word tiles only).
SEEDS: dict[str, list[str]] = {
    # ---------------- EASY ----------------
    "color": [
        "red", "orange", "yellow", "green", "blue", "indigo", "violet", "purple",
        "pink", "magenta", "cyan", "teal", "turquoise", "aqua", "navy", "azure",
        "black", "white", "gray", "grey", "brown", "tan", "beige", "ivory",
        "cream", "gold", "silver", "bronze", "copper", "maroon", "crimson",
        "scarlet", "ruby", "rose", "salmon", "coral", "peach", "amber", "lemon",
        "lime", "mint", "olive", "emerald", "jade", "forest", "sage", "khaki",
        "mustard", "ochre", "rust", "sienna", "umber", "fuchsia", "lavender",
        "lilac", "plum", "mauve", "periwinkle", "cobalt", "sapphire", "denim",
        "charcoal", "ebony", "onyx", "pearl", "snow", "alabaster",
    ],
    "fruit": [
        "apple", "banana", "orange", "pear", "peach", "plum", "cherry", "grape",
        "lemon", "lime", "melon", "watermelon", "cantaloupe", "honeydew",
        "mango", "papaya", "pineapple", "kiwi", "guava", "lychee", "passionfruit",
        "apricot", "nectarine", "pomegranate", "fig", "date", "raisin",
        "strawberry", "raspberry", "blueberry", "blackberry", "cranberry",
        "boysenberry", "gooseberry", "elderberry", "currant", "rhubarb",
        "tangerine", "mandarin", "clementine", "grapefruit", "kumquat",
        "starfruit", "dragonfruit", "jackfruit", "durian", "rambutan", "longan",
        "persimmon", "quince", "olive", "avocado", "tomato", "coconut",
    ],
    "vehicle": [
        "car", "truck", "van", "bus", "minivan", "sedan", "coupe", "hatchback",
        "convertible", "wagon", "suv", "jeep", "limo", "limousine", "taxi",
        "cab", "tractor", "trailer", "semi", "lorry", "pickup", "rv", "camper",
        "motorcycle", "bike", "bicycle", "scooter", "moped", "skateboard",
        "boat", "ship", "yacht", "canoe", "kayak", "raft", "sailboat",
        "submarine", "ferry", "barge", "dinghy", "schooner", "tugboat",
        "plane", "airplane", "jet", "helicopter", "glider", "blimp", "zeppelin",
        "rocket", "spaceship", "shuttle", "drone", "balloon", "train",
        "tram", "trolley", "subway", "monorail", "locomotive", "carriage",
        "wagon", "sled", "sleigh", "scooter", "unicycle", "tricycle",
        "ambulance", "firetruck", "tank", "hovercraft", "snowmobile",
    ],
    "sports": [
        "soccer", "football", "basketball", "baseball", "softball", "volleyball",
        "tennis", "badminton", "squash", "racquetball", "pickleball", "cricket",
        "rugby", "lacrosse", "hockey", "handball", "polo", "golf", "bowling",
        "boxing", "wrestling", "judo", "karate", "taekwondo", "kickboxing",
        "fencing", "archery", "shooting", "darts", "billiards", "snooker",
        "swimming", "diving", "surfing", "rowing", "sailing", "kayaking",
        "skating", "skiing", "snowboarding", "sledding", "curling", "luge",
        "running", "jogging", "cycling", "triathlon", "marathon", "decathlon",
        "gymnastics", "climbing", "hiking", "yoga", "pilates", "crossfit",
        "skydiving", "parkour", "fishing", "hunting", "equestrian",
    ],
    "weather": [
        "sun", "sunny", "rain", "rainy", "snow", "snowy", "wind", "windy",
        "cloud", "cloudy", "fog", "foggy", "mist", "misty", "haze", "hazy",
        "storm", "stormy", "thunder", "lightning", "hail", "sleet", "drizzle",
        "shower", "downpour", "blizzard", "hurricane", "tornado", "cyclone",
        "typhoon", "monsoon", "tempest", "gale", "breeze", "gust", "draft",
        "hot", "warm", "cool", "cold", "freezing", "frost", "frosty", "ice",
        "icy", "humid", "humidity", "dry", "arid", "wet", "damp", "muggy",
        "sultry", "balmy", "crisp", "clear", "overcast", "gloomy", "sunshine",
        "rainbow", "dew", "drought", "flood", "heatwave", "chill",
    ],
    "body_part": [
        "head", "hair", "scalp", "face", "forehead", "eye", "eyes", "eyebrow",
        "eyelash", "eyelid", "ear", "ears", "nose", "nostril", "mouth", "lip",
        "lips", "tongue", "tooth", "teeth", "gum", "chin", "jaw", "cheek",
        "neck", "throat", "shoulder", "arm", "elbow", "forearm", "wrist",
        "hand", "palm", "finger", "thumb", "knuckle", "nail", "fingernail",
        "chest", "breast", "back", "spine", "rib", "stomach", "belly",
        "abdomen", "waist", "hip", "buttock", "thigh", "leg", "knee", "shin",
        "calf", "ankle", "foot", "feet", "heel", "toe", "sole", "skin",
        "muscle", "bone", "blood", "vein", "artery", "heart", "lung",
        "liver", "kidney", "brain", "nerve", "tendon",
    ],
    "clothing": [
        "shirt", "tshirt", "blouse", "tank", "tunic", "jersey", "sweater",
        "hoodie", "cardigan", "vest", "jacket", "coat", "blazer", "parka",
        "raincoat", "trenchcoat", "windbreaker", "poncho", "cape", "shawl",
        "pants", "trousers", "jeans", "slacks", "leggings", "shorts", "skirt",
        "dress", "gown", "robe", "kimono", "sari", "kilt", "uniform", "suit",
        "tuxedo", "pajamas", "nightgown", "underwear", "bra", "panties",
        "boxers", "briefs", "socks", "stockings", "tights", "pantyhose",
        "shoe", "shoes", "boot", "boots", "sneaker", "sneakers", "sandal",
        "sandals", "slipper", "slippers", "heel", "heels", "loafer", "moccasin",
        "hat", "cap", "beanie", "beret", "fedora", "helmet", "scarf", "tie",
        "bowtie", "belt", "glove", "gloves", "mitten", "mittens",
    ],
    "room": [
        "kitchen", "bedroom", "bathroom", "lavatory", "powder", "living",
        "lounge", "den", "study", "office", "library", "parlor", "salon",
        "dining", "pantry", "scullery", "foyer", "entry", "entryway", "hall",
        "hallway", "corridor", "stairway", "landing", "vestibule", "mudroom",
        "laundry", "utility", "garage", "basement", "cellar", "attic", "loft",
        "nursery", "playroom", "gameroom", "garret", "conservatory", "atrium",
        "veranda", "porch", "patio", "balcony", "deck", "sunroom", "solarium",
        "bedchamber", "boudoir", "closet", "wardrobe", "workshop", "studio",
        "gym", "sauna", "spa", "ballroom", "chapel", "chamber",
    ],
    "beverage": [
        "water", "milk", "juice", "soda", "pop", "cola", "lemonade", "tea",
        "coffee", "espresso", "latte", "cappuccino", "mocha", "macchiato",
        "smoothie", "shake", "milkshake", "cocoa", "chocolate", "punch",
        "cider", "lemonade", "limeade", "tonic", "seltzer", "sparkling",
        "wine", "beer", "ale", "lager", "stout", "porter", "pilsner", "cider",
        "champagne", "sake", "mead", "brandy", "whiskey", "vodka", "gin",
        "rum", "tequila", "scotch", "bourbon", "cognac", "liqueur", "absinthe",
        "cocktail", "martini", "margarita", "mojito", "daiquiri", "sangria",
        "kombucha", "kefir", "lassi", "horchata", "atole", "matcha", "chai",
    ],
    "vegetable": [
        "carrot", "potato", "tomato", "onion", "garlic", "celery", "lettuce",
        "spinach", "kale", "cabbage", "broccoli", "cauliflower", "asparagus",
        "artichoke", "cucumber", "zucchini", "squash", "pumpkin", "eggplant",
        "pepper", "chili", "jalapeno", "radish", "turnip", "beet", "parsnip",
        "rutabaga", "yam", "sweetpotato", "leek", "shallot", "scallion",
        "chive", "fennel", "endive", "arugula", "watercress", "okra", "corn",
        "pea", "peas", "bean", "beans", "lentil", "chickpea", "soybean",
        "edamame", "mushroom", "truffle", "ginger", "horseradish", "wasabi",
    ],
    "toys": [
        "doll", "puppet", "marionette", "teddy", "bear", "plush", "stuffed",
        "ball", "blocks", "lego", "puzzle", "jigsaw", "kite", "yoyo", "frisbee",
        "boomerang", "marble", "marbles", "jacks", "top", "spinner", "drone",
        "robot", "rocket", "car", "truck", "train", "plane", "boat", "soldier",
        "figurine", "action", "doll", "house", "dollhouse", "playhouse",
        "swing", "slide", "trampoline", "hoop", "scooter", "skateboard",
        "tricycle", "wagon", "sled", "sleigh", "rocking", "horse", "hobby",
        "drum", "xylophone", "whistle", "rattle", "bubble", "bubbles", "chalk",
        "crayon", "crayons", "clay", "playdough", "slime", "kaleidoscope",
        "puzzle", "checkers", "chess", "monopoly", "scrabble", "domino",
    ],
    "month": [
        "january", "february", "march", "april", "may", "june", "july",
        "august", "september", "october", "november", "december",
    ],
    "holiday": [
        "christmas", "easter", "halloween", "thanksgiving", "hanukkah",
        "kwanzaa", "diwali", "passover", "ramadan", "eid", "purim", "yom",
        "kippur", "rosh", "hashanah", "advent", "epiphany", "pentecost",
        "lent", "carnival", "mardi", "gras", "valentines", "patricks",
        "patrick", "halloween", "newyear", "yule", "solstice", "equinox",
        "memorial", "labor", "independence", "veterans", "presidents",
        "columbus", "juneteenth", "boxing", "anzac", "bastille", "canada",
        "queens", "kings", "anniversary", "birthday", "wedding", "festival",
        "holi", "vesak", "obon", "lunar", "tet", "songkran",
    ],
    "snack_food": [
        "chips", "crisps", "pretzels", "popcorn", "crackers", "nuts", "almonds",
        "cashews", "peanuts", "pistachios", "walnuts", "pecans", "raisins",
        "trailmix", "granola", "bar", "cookies", "biscuits", "wafers",
        "candy", "chocolate", "gummies", "jellybeans", "lollipop", "lollipops",
        "mints", "toffee", "fudge", "marshmallow", "marshmallows", "pop",
        "popsicles", "icecream", "sherbet", "sorbet", "yogurt", "cheese",
        "string", "stringcheese", "jerky", "raisin", "fruit", "apple",
        "banana", "orange", "carrot", "celery", "hummus", "salsa", "dip",
        "guacamole", "queso", "nachos", "tacos", "pizza", "sandwich", "wrap",
        "muffin", "scone", "donut", "doughnut", "danish", "croissant",
        "bagel", "pretzel", "churro",
    ],
    "dessert_food": [
        "cake", "cupcake", "cheesecake", "shortcake", "pancake", "fruitcake",
        "pie", "tart", "cobbler", "crumble", "crisp", "trifle", "pudding",
        "custard", "flan", "creme", "mousse", "souffle", "parfait", "sundae",
        "icecream", "gelato", "sherbet", "sorbet", "frozen", "yogurt", "popsicle",
        "cookie", "biscuit", "brownie", "blondie", "macaroon", "macaron",
        "meringue", "eclair", "profiterole", "strudel", "baklava", "tiramisu",
        "donut", "doughnut", "danish", "croissant", "muffin", "scone",
        "pastry", "pastries", "tart", "tartlet", "candy", "chocolate",
        "fudge", "truffle", "praline", "toffee", "caramel", "brittle",
        "marshmallow", "lollipop", "gummy", "jellybean", "licorice", "taffy",
        "mochi", "halva", "marzipan", "nougat", "panna", "cotta", "cannoli",
        "biscotti", "rugelach", "kolache", "churro",
    ],

    # ---------------- MEDIUM ----------------
    "farm_animals": [
        "cow", "calf", "bull", "ox", "oxen", "cattle", "heifer", "steer",
        "horse", "mare", "stallion", "foal", "colt", "filly", "pony",
        "donkey", "mule", "burro", "ass", "pig", "sow", "boar", "piglet",
        "hog", "swine", "sheep", "ram", "ewe", "lamb", "goat", "kid", "billy",
        "nanny", "chicken", "rooster", "hen", "chick", "cockerel", "pullet",
        "duck", "drake", "duckling", "goose", "gander", "gosling", "turkey",
        "tom", "poult", "rabbit", "doe", "buck", "kit", "alpaca", "llama",
        "yak", "buffalo", "bison", "ostrich", "emu", "peacock", "guineafowl",
        "dog", "cat", "kitten", "puppy", "pigeon", "dove",
    ],
    "pets": [
        "dog", "puppy", "cat", "kitten", "rabbit", "bunny", "hamster",
        "guinea", "gerbil", "mouse", "rat", "ferret", "chinchilla", "hedgehog",
        "fish", "goldfish", "guppy", "betta", "tetra", "cichlid", "koi",
        "turtle", "tortoise", "lizard", "gecko", "iguana", "chameleon",
        "snake", "python", "boa", "frog", "toad", "salamander", "newt",
        "axolotl", "tarantula", "spider", "scorpion", "crab", "hermit",
        "shrimp", "snail", "bird", "parrot", "parakeet", "budgie", "cockatiel",
        "cockatoo", "macaw", "lovebird", "canary", "finch", "dove", "pigeon",
        "chicken", "duck", "horse", "pony",
    ],
    "ocean_animals": [
        "fish", "shark", "whale", "dolphin", "porpoise", "orca", "narwhal",
        "beluga", "manatee", "dugong", "seal", "sealion", "walrus", "otter",
        "octopus", "squid", "cuttlefish", "nautilus", "jellyfish", "anemone",
        "coral", "sponge", "starfish", "urchin", "crab", "lobster", "shrimp",
        "prawn", "crayfish", "barnacle", "clam", "mussel", "oyster", "scallop",
        "conch", "snail", "slug", "tuna", "salmon", "cod", "haddock",
        "halibut", "flounder", "sole", "bass", "trout", "marlin", "swordfish",
        "sailfish", "sardine", "anchovy", "herring", "mackerel", "barracuda",
        "eel", "moray", "stingray", "manta", "ray", "skate", "seahorse",
        "pipefish", "puffer", "pufferfish", "lionfish", "angler", "wrasse",
        "grouper", "snapper", "minnow",
    ],
    "birds": [
        "robin", "sparrow", "finch", "wren", "warbler", "thrush", "blackbird",
        "starling", "grackle", "jay", "bluejay", "magpie", "crow", "raven",
        "rook", "jackdaw", "cardinal", "oriole", "tanager", "bunting",
        "chickadee", "titmouse", "nuthatch", "creeper", "swallow", "martin",
        "swift", "hummingbird", "kingfisher", "woodpecker", "flicker",
        "owl", "eagle", "hawk", "falcon", "kestrel", "kite", "harrier",
        "buzzard", "vulture", "condor", "osprey", "duck", "mallard", "teal",
        "pintail", "wigeon", "goose", "swan", "loon", "grebe", "pelican",
        "cormorant", "heron", "egret", "stork", "ibis", "spoonbill",
        "flamingo", "crane", "rail", "coot", "moorhen", "gull", "tern",
        "puffin", "auk", "albatross", "petrel", "parrot", "parakeet",
        "macaw", "cockatoo", "cockatiel", "lovebird", "budgie", "canary",
        "ostrich", "emu", "kiwi", "cassowary", "rhea", "peacock", "pheasant",
        "quail", "partridge", "grouse", "turkey", "chicken", "pigeon", "dove",
    ],
    "flower": [
        "rose", "tulip", "lily", "daisy", "daffodil", "sunflower", "orchid",
        "iris", "peony", "poppy", "carnation", "chrysanthemum", "marigold",
        "petunia", "pansy", "violet", "hibiscus", "jasmine", "lotus",
        "magnolia", "azalea", "rhododendron", "camellia", "hydrangea",
        "wisteria", "lavender", "lilac", "honeysuckle", "geranium", "begonia",
        "impatiens", "snapdragon", "zinnia", "dahlia", "freesia", "anemone",
        "bluebell", "buttercup", "dandelion", "clover", "primrose", "cosmos",
        "morning", "glory", "amaryllis", "anthurium", "bird", "paradise",
        "calendula", "celosia", "columbine", "coneflower", "coreopsis",
        "crocus", "cyclamen", "delphinium", "foxglove", "gardenia", "gerbera",
        "gladiolus", "heliotrope", "hyacinth", "larkspur", "nasturtium",
        "oleander", "phlox", "ranunculus", "salvia", "verbena", "yarrow",
    ],
    "tree": [
        "oak", "maple", "elm", "birch", "beech", "ash", "alder", "aspen",
        "poplar", "willow", "cottonwood", "sycamore", "chestnut", "hickory",
        "walnut", "pecan", "hazel", "cherry", "apple", "pear", "plum",
        "peach", "apricot", "fig", "olive", "lemon", "lime", "orange",
        "mango", "papaya", "avocado", "coconut", "palm", "date", "pine",
        "spruce", "fir", "cedar", "cypress", "juniper", "yew", "redwood",
        "sequoia", "hemlock", "larch", "tamarack", "magnolia", "dogwood",
        "redbud", "ginkgo", "eucalyptus", "acacia", "baobab", "banyan",
        "rubber", "teak", "mahogany", "ebony", "rosewood", "sandalwood",
        "balsa", "bamboo", "cork", "linden", "locust", "mulberry", "myrtle",
        "rowan", "tupelo",
    ],
    "furniture": [
        "chair", "armchair", "rocker", "recliner", "stool", "bench", "ottoman",
        "footstool", "sofa", "couch", "loveseat", "settee", "divan", "futon",
        "chaise", "table", "desk", "counter", "vanity", "console", "buffet",
        "sideboard", "credenza", "hutch", "cabinet", "cupboard", "wardrobe",
        "armoire", "dresser", "chest", "bureau", "nightstand", "bookcase",
        "shelf", "shelving", "etagere", "rack", "stand", "bed", "bunk",
        "crib", "cot", "hammock", "cradle", "bassinet", "headboard", "footboard",
        "mattress", "pillow", "cushion", "lamp", "chandelier", "sconce",
        "mirror", "rug", "carpet", "curtain", "drape", "blind", "shade",
        "screen", "easel", "piano", "organ", "highchair", "playpen",
    ],
    "technology": [
        "computer", "laptop", "desktop", "tablet", "phone", "smartphone",
        "iphone", "android", "ipad", "smartwatch", "fitbit", "headphones",
        "earbuds", "speaker", "microphone", "camera", "webcam", "scanner",
        "printer", "monitor", "screen", "display", "keyboard", "mouse",
        "trackpad", "joystick", "controller", "console", "router", "modem",
        "server", "database", "internet", "wifi", "bluetooth", "cable",
        "charger", "battery", "drive", "harddrive", "ssd", "memory", "ram",
        "processor", "cpu", "gpu", "chip", "circuit", "motherboard", "card",
        "software", "hardware", "firmware", "app", "application", "program",
        "code", "algorithm", "encryption", "password", "username", "login",
        "browser", "email", "website", "blog", "podcast", "stream",
        "download", "upload", "wireless", "network", "cloud", "data",
        "robot", "drone", "satellite", "telescope", "microscope",
    ],
    "game": [
        "chess", "checkers", "backgammon", "scrabble", "monopoly", "clue",
        "risk", "trouble", "sorry", "battleship", "candyland", "uno",
        "spades", "hearts", "bridge", "poker", "blackjack", "solitaire",
        "rummy", "canasta", "cribbage", "pinochle", "euchre", "war",
        "concentration", "memory", "go", "shogi", "mahjong", "dominoes",
        "yahtzee", "boggle", "pictionary", "charades", "trivia", "jeopardy",
        "tag", "hide", "seek", "freeze", "redrover", "duck", "goose",
        "marbles", "jacks", "hopscotch", "marco", "polo", "twister",
        "sudoku", "crossword", "wordsearch", "jigsaw", "puzzle", "tetris",
        "minecraft", "fortnite", "roblox", "pokemon", "mario", "zelda",
        "pacman", "frogger", "pong", "asteroids", "donkey", "kong",
        "bingo", "lotto", "raffle", "darts", "billiards", "snooker", "pool",
        "curling", "horseshoes", "bocce", "petanque", "shuffleboard",
    ],
    "movie": [
        "comedy", "drama", "thriller", "horror", "romance", "action",
        "adventure", "fantasy", "sci", "scifi", "mystery", "musical",
        "documentary", "western", "noir", "biopic", "epic", "war",
        "animated", "cartoon", "silent", "indie", "blockbuster", "sequel",
        "prequel", "remake", "reboot", "trilogy", "saga", "franchise",
        "screenplay", "script", "scene", "shot", "take", "cut", "edit",
        "director", "producer", "writer", "actor", "actress", "star",
        "cast", "crew", "extra", "stunt", "double", "premiere", "release",
        "theater", "cinema", "screen", "projector", "popcorn", "ticket",
        "trailer", "preview", "credits", "cameo", "sequence", "montage",
        "studio", "set", "location", "costume", "makeup", "props",
        "soundtrack", "score", "oscar", "emmy", "golden", "globe",
        "hollywood", "bollywood", "festival", "premiere",
    ],
    "school_supply": [
        "pencil", "pen", "marker", "highlighter", "crayon", "chalk", "eraser",
        "ruler", "protractor", "compass", "calculator", "stapler", "staples",
        "tape", "scissors", "glue", "paste", "paper", "notebook", "binder",
        "folder", "portfolio", "envelope", "clipboard", "notepad", "journal",
        "planner", "agenda", "diary", "textbook", "workbook", "dictionary",
        "thesaurus", "atlas", "globe", "map", "chart", "poster", "easel",
        "whiteboard", "blackboard", "chalkboard", "marker", "duster", "bag",
        "backpack", "satchel", "lunchbox", "thermos", "bottle", "lock",
        "locker", "desk", "chair", "computer", "tablet", "laptop", "printer",
        "scanner", "stamp", "ink", "cartridge", "punch", "clip", "paperclip",
        "rubberband", "thumbtack", "pushpin",
    ],
    "breakfast_food": [
        "pancake", "waffle", "crepe", "french", "toast", "bagel", "muffin",
        "scone", "biscuit", "croissant", "danish", "donut", "doughnut",
        "cereal", "oatmeal", "porridge", "grits", "granola", "muesli",
        "yogurt", "parfait", "fruit", "banana", "apple", "berry", "berries",
        "egg", "eggs", "omelet", "omelette", "scramble", "scrambled",
        "poached", "boiled", "fried", "frittata", "quiche", "benedict",
        "bacon", "sausage", "ham", "spam", "kipper", "smoked", "salmon",
        "lox", "hash", "browns", "potato", "potatoes", "tater", "tots",
        "toast", "bread", "english", "tortilla", "burrito", "taco",
        "milk", "juice", "coffee", "tea", "cocoa", "smoothie", "shake",
        "butter", "jam", "jelly", "marmalade", "honey", "syrup", "maple",
        "nutella",
    ],
    "nature": [
        "tree", "forest", "jungle", "woods", "meadow", "field", "prairie",
        "grassland", "savanna", "desert", "tundra", "swamp", "marsh",
        "wetland", "bog", "fen", "mountain", "hill", "valley", "canyon",
        "gorge", "ravine", "cliff", "cave", "cavern", "grotto", "river",
        "stream", "creek", "brook", "pond", "lake", "ocean", "sea", "bay",
        "gulf", "lagoon", "reef", "coast", "shore", "beach", "dune",
        "island", "peninsula", "cape", "isthmus", "atoll", "archipelago",
        "rock", "stone", "boulder", "pebble", "sand", "soil", "dirt", "mud",
        "clay", "gravel", "leaf", "flower", "grass", "weed", "moss", "fern",
        "vine", "shrub", "bush", "bark", "root", "branch", "twig", "seed",
        "fruit", "nut", "berry", "mushroom", "fungus", "algae", "lichen",
        "rain", "snow", "wind", "sun", "moon", "star", "cloud", "rainbow",
        "thunder", "lightning", "hurricane", "tornado", "earthquake",
        "volcano", "geyser", "waterfall", "glacier", "iceberg",
    ],
    "makeup": [
        "lipstick", "lipgloss", "lipliner", "balm", "chapstick", "blush",
        "rouge", "bronzer", "highlighter", "contour", "concealer", "foundation",
        "powder", "primer", "setting", "spray", "mascara", "eyeliner",
        "eyeshadow", "shadow", "liner", "kohl", "brow", "pencil", "gel",
        "tweezers", "curler", "lash", "lashes", "false", "extension",
        "polish", "lacquer", "topcoat", "basecoat", "remover", "acetone",
        "perfume", "cologne", "fragrance", "scent", "deodorant", "lotion",
        "moisturizer", "serum", "cleanser", "toner", "exfoliant", "scrub",
        "mask", "peel", "cream", "butter", "oil", "balm", "salve",
        "brush", "sponge", "puff", "applicator", "compact", "palette",
        "kit", "case", "bag", "mirror",
    ],
    "playground_equipment": [
        "swing", "slide", "seesaw", "teetertotter", "merry", "carousel",
        "roundabout", "spinner", "monkey", "bars", "ladder", "rope", "net",
        "climber", "climbing", "frame", "wall", "rock", "boulder", "tunnel",
        "tube", "bridge", "tightrope", "balance", "beam", "trampoline",
        "bouncer", "bouncy", "spring", "rocker", "rider", "horse", "spinner",
        "sandbox", "sand", "pit", "playhouse", "fort", "castle", "treehouse",
        "tower", "platform", "deck", "ramp", "stairs", "steps", "pole",
        "firepole", "zipline", "hammock", "swing", "tire", "tireswing",
        "hopscotch", "chalk", "ball", "hoop", "basket", "goal", "net",
        "frisbee", "kite", "scooter", "skateboard", "tricycle", "wagon",
        "kid", "child", "park", "yard",
    ],

    # ---------------- HARD ----------------
    "space": [
        "sun", "moon", "star", "stars", "planet", "earth", "mars", "venus",
        "mercury", "jupiter", "saturn", "uranus", "neptune", "pluto", "ceres",
        "eris", "comet", "asteroid", "meteor", "meteorite", "meteoroid",
        "galaxy", "nebula", "quasar", "pulsar", "supernova", "blackhole",
        "wormhole", "constellation", "orbit", "gravity", "cosmos", "universe",
        "void", "vacuum", "atmosphere", "stratosphere", "ionosphere",
        "rocket", "shuttle", "satellite", "probe", "lander", "rover",
        "telescope", "observatory", "spacecraft", "spaceship", "spaceman",
        "astronaut", "cosmonaut", "alien", "ufo", "hubble", "voyager",
        "apollo", "soyuz", "mir", "skylab", "iss", "spacex", "nasa", "esa",
        "lunar", "solar", "stellar", "interstellar", "celestial", "zodiac",
        "aries", "taurus", "gemini", "cancer", "leo", "virgo", "libra",
        "scorpio", "sagittarius", "capricorn", "aquarius", "pisces",
        "eclipse", "transit", "aurora", "crater", "ring", "asteroid",
    ],
    "math": [
        "add", "addition", "sum", "plus", "subtract", "subtraction", "minus",
        "difference", "multiply", "multiplication", "product", "times",
        "divide", "division", "quotient", "remainder", "fraction", "decimal",
        "percent", "percentage", "ratio", "proportion", "average", "mean",
        "median", "mode", "range", "variance", "standard", "deviation",
        "number", "integer", "natural", "whole", "rational", "irrational",
        "real", "imaginary", "complex", "prime", "composite", "even", "odd",
        "negative", "positive", "zero", "infinity", "digit", "numeral",
        "equation", "inequality", "expression", "variable", "constant",
        "coefficient", "term", "factor", "polynomial", "monomial", "binomial",
        "trinomial", "quadratic", "linear", "exponent", "power", "root",
        "square", "cube", "log", "logarithm", "sine", "cosine", "tangent",
        "secant", "cosecant", "cotangent", "angle", "degree", "radian",
        "triangle", "square", "rectangle", "circle", "oval", "ellipse",
        "polygon", "pentagon", "hexagon", "octagon", "trapezoid", "rhombus",
        "parallelogram", "sphere", "cube", "cylinder", "cone", "pyramid",
        "geometry", "algebra", "calculus", "trigonometry", "statistics",
        "probability", "topology", "matrix", "vector", "scalar", "set",
        "subset", "union", "intersection", "function", "graph",
    ],
    "science": [
        "physics", "chemistry", "biology", "geology", "astronomy", "ecology",
        "botany", "zoology", "anatomy", "physiology", "neurology", "genetics",
        "microbiology", "biochemistry", "pharmacology", "psychology",
        "sociology", "anthropology", "archaeology", "paleontology",
        "meteorology", "climatology", "oceanography", "seismology", "volcanology",
        "atom", "molecule", "element", "compound", "mixture", "solution",
        "proton", "neutron", "electron", "ion", "nucleus", "isotope",
        "energy", "force", "mass", "weight", "velocity", "acceleration",
        "gravity", "friction", "pressure", "temperature", "heat", "light",
        "sound", "wave", "frequency", "wavelength", "amplitude", "current",
        "voltage", "resistance", "circuit", "magnet", "magnetism", "field",
        "cell", "tissue", "organ", "organism", "species", "genus", "family",
        "kingdom", "phylum", "class", "order", "habitat", "ecosystem",
        "biome", "evolution", "adaptation", "selection", "mutation", "gene",
        "chromosome", "dna", "rna", "protein", "enzyme", "hormone",
        "experiment", "hypothesis", "theory", "law", "observation", "data",
        "analysis", "lab", "laboratory", "microscope", "telescope", "beaker",
        "flask", "burner", "graduate", "pipette", "petri",
    ],
    "boys_first_names": [
        "aaron", "adam", "adrian", "aiden", "alan", "albert", "alex",
        "alexander", "alfred", "andrew", "anthony", "antonio", "arthur",
        "austin", "avery", "barry", "ben", "benjamin", "bennett", "bernard",
        "blake", "bobby", "brad", "bradley", "brandon", "brian", "bruce",
        "bryan", "caleb", "calvin", "cameron", "carl", "carlos", "carter",
        "charles", "charlie", "chase", "chris", "christian", "christopher",
        "clark", "claude", "clifford", "clinton", "cole", "colin", "connor",
        "craig", "curtis", "dale", "daniel", "danny", "darren", "david",
        "dean", "dennis", "derek", "devin", "dexter", "dillon", "dominic",
        "donald", "douglas", "drew", "duncan", "dustin", "dylan", "earl",
        "eddie", "edgar", "edward", "edwin", "elijah", "elliot", "ellis",
        "emmanuel", "eric", "ernest", "ethan", "eugene", "evan", "everett",
        "felix", "francis", "frank", "franklin", "fred", "frederick",
        "gabriel", "gary", "george", "gerald", "gilbert", "glen", "gordon",
        "grant", "greg", "gregory", "harold", "harry", "harvey", "henry",
        "herbert", "howard", "hugh", "hunter", "ian", "isaac", "isaiah",
        "ivan", "jack", "jackson", "jacob", "jake", "james", "jamie",
        "jared", "jason", "jasper", "jay", "jeffrey", "jeremiah", "jeremy",
        "jerry", "jesse", "jim", "joel", "john", "johnny", "jonah",
        "jonathan", "jordan", "jose", "joseph", "joshua", "juan", "judah",
        "julian", "justin", "keith", "kelvin", "ken", "kenneth", "kevin",
        "kyle", "lance", "larry", "lawrence", "leo", "leonard", "leroy",
        "leslie", "levi", "lewis", "liam", "lincoln", "logan", "louis",
        "lucas", "luke", "luther", "malcolm", "manuel", "marcus", "mario",
        "mark", "martin", "marvin", "mason", "matthew", "maurice", "max",
        "michael", "miguel", "milton", "mitchell", "morgan", "morris",
        "moses", "murray", "nathan", "nathaniel", "neil", "nelson", "nicholas",
        "noah", "norman", "oliver", "oscar", "owen", "patrick", "paul",
        "perry", "peter", "philip", "phillip", "preston", "quentin", "ralph",
        "randall", "randy", "raymond", "reginald", "rene", "richard", "rick",
        "ricky", "robert", "roberto", "rodney", "roger", "roland", "ronald",
        "ronnie", "roy", "russell", "ryan", "sam", "samuel", "scott",
        "sean", "sebastian", "sergio", "seth", "shane", "shawn", "sidney",
        "simon", "stanley", "stephen", "steven", "stuart", "ted", "terry",
        "theodore", "thomas", "timothy", "todd", "tom", "tommy", "tony",
        "travis", "trevor", "tyler", "tyrone", "vernon", "victor", "vincent",
        "wade", "walter", "warren", "wayne", "wesley", "william", "willie",
        "wyatt", "xavier", "zachary", "zane",
    ],
    "girls_first_names": [
        "abigail", "ada", "adelaide", "adrienne", "agatha", "agnes", "aileen",
        "alana", "alexandra", "alexis", "alice", "alicia", "alison", "allison",
        "alma", "amanda", "amber", "amelia", "amy", "andrea", "angela",
        "angelica", "angelina", "anita", "ann", "anna", "anne", "annette",
        "annie", "anya", "april", "ariana", "arlene", "ashley", "audrey",
        "ava", "barbara", "beatrice", "becky", "belinda", "bella", "bernice",
        "beth", "bethany", "betty", "beverly", "bianca", "blanche", "bonnie",
        "brandi", "brenda", "bridget", "brittany", "brooke", "caitlin",
        "camille", "candace", "candice", "cara", "carla", "carmen", "carol",
        "caroline", "carolyn", "carrie", "casey", "cassandra", "catherine",
        "cecilia", "celeste", "celia", "charlotte", "chelsea", "cherry",
        "cheryl", "chloe", "christina", "christine", "cindy", "claire",
        "clara", "clarissa", "claudia", "colleen", "connie", "constance",
        "courtney", "crystal", "cynthia", "daisy", "dana", "danielle",
        "daphne", "darlene", "dawn", "deanna", "deborah", "debra", "delia",
        "denise", "diana", "diane", "dixie", "dolores", "donna", "doreen",
        "doris", "dorothy", "edith", "edna", "eileen", "elaine", "eleanor",
        "elena", "eliza", "elizabeth", "ella", "ellen", "elsa", "elsie",
        "emily", "emma", "erica", "erika", "erin", "esmeralda", "estelle",
        "esther", "ethel", "eugenia", "eunice", "eva", "evelyn", "faith",
        "fatima", "fay", "felicia", "fiona", "florence", "frances", "freda",
        "gail", "gemma", "geneva", "genevieve", "georgia", "geraldine",
        "gertrude", "gina", "ginger", "gladys", "glenda", "gloria", "grace",
        "gretchen", "gwen", "gwendolyn", "hannah", "harriet", "hazel",
        "heather", "heidi", "helen", "helena", "henrietta", "hilda", "holly",
        "hope", "ida", "imogene", "ingrid", "irene", "iris", "isabel",
        "isabella", "ivy", "jacqueline", "jamie", "jane", "janet", "janice",
        "janis", "jasmine", "jean", "jeanette", "jeanne", "jenna", "jennifer",
        "jenny", "jessica", "jewel", "jill", "joan", "joanna", "joanne",
        "jocelyn", "jodi", "joy", "joyce", "judith", "judy", "julia",
        "julie", "juliet", "june", "justine", "kara", "karen", "kate",
        "katelyn", "katherine", "kathleen", "kathryn", "kathy", "katie",
        "katrina", "kayla", "kelly", "kelsey", "kendra", "kim", "kimberly",
        "kira", "kirsten", "krista", "kristen", "kristin", "kristina",
        "kristy", "lacey", "laura", "lauren", "laurie", "leah", "leigh",
        "lena", "leona", "leslie", "leticia", "lila", "lillian", "lily",
        "linda", "lindsey", "lisa", "liza", "lola", "loretta", "lori",
        "lorraine", "louisa", "louise", "lucia", "lucille", "lucy", "luella",
        "lydia", "lynn", "mabel", "madeline", "madonna", "maggie", "marcia",
        "margaret", "margie", "maria", "marian", "marie", "marilyn",
        "marion", "marjorie", "martha", "mary", "matilda", "maureen",
        "maxine", "may", "megan", "melanie", "melinda", "melissa", "melody",
        "mercedes", "meredith", "mia", "michelle", "mildred", "millie",
        "minnie", "miranda", "miriam", "misty", "molly", "mona", "monica",
        "muriel", "myra", "myrtle", "nadia", "nancy", "naomi", "natalie",
        "natasha", "nellie", "nettie", "nichole", "nicole", "nina", "nora",
        "norma", "olga", "olive", "olivia", "opal", "ophelia", "pamela",
        "patricia", "patsy", "patty", "paula", "pauline", "pearl", "peggy",
        "penelope", "phoebe", "phyllis", "polly", "priscilla", "rachel",
        "rebecca", "regina", "renee", "rhoda", "rhonda", "rita", "roberta",
        "robin", "rochelle", "rose", "rosemary", "ruby", "ruth", "sabrina",
        "sally", "samantha", "sandra", "sandy", "sara", "sarah", "savannah",
        "selena", "shannon", "sharon", "sheila", "shelby", "sheri", "sherri",
        "shirley", "sierra", "silvia", "sofia", "sonia", "sonya", "sophia",
        "stacey", "stacy", "stella", "stephanie", "sue", "susan", "susanna",
        "suzanne", "sybil", "sylvia", "tabitha", "tamara", "tammy", "tania",
        "tanya", "tara", "teresa", "thelma", "theresa", "tiffany", "tina",
        "tonya", "tracey", "tracy", "trisha", "ursula", "valerie", "vanessa",
        "vera", "veronica", "vicki", "vickie", "victoria", "violet",
        "virginia", "vivian", "wanda", "wendy", "whitney", "wilma", "winifred",
        "yolanda", "yvette", "yvonne", "zelda", "zoe",
    ],
    "countries": [
        "afghanistan", "albania", "algeria", "andorra", "angola", "argentina",
        "armenia", "australia", "austria", "azerbaijan", "bahrain", "bangladesh",
        "belarus", "belgium", "belize", "benin", "bhutan", "bolivia",
        "botswana", "brazil", "brunei", "bulgaria", "burundi", "cambodia",
        "cameroon", "canada", "chad", "chile", "china", "colombia", "comoros",
        "congo", "croatia", "cuba", "cyprus", "denmark", "djibouti", "ecuador",
        "egypt", "england", "eritrea", "estonia", "ethiopia", "fiji",
        "finland", "france", "gabon", "gambia", "georgia", "germany", "ghana",
        "greece", "grenada", "guatemala", "guinea", "guyana", "haiti",
        "honduras", "hungary", "iceland", "india", "indonesia", "iran",
        "iraq", "ireland", "israel", "italy", "jamaica", "japan", "jordan",
        "kazakhstan", "kenya", "kiribati", "kosovo", "kuwait", "laos",
        "latvia", "lebanon", "lesotho", "liberia", "libya", "lithuania",
        "luxembourg", "madagascar", "malawi", "malaysia", "maldives", "mali",
        "malta", "mauritania", "mauritius", "mexico", "micronesia", "moldova",
        "monaco", "mongolia", "montenegro", "morocco", "mozambique", "myanmar",
        "namibia", "nauru", "nepal", "netherlands", "nicaragua", "niger",
        "nigeria", "norway", "oman", "pakistan", "palau", "panama", "paraguay",
        "peru", "philippines", "poland", "portugal", "qatar", "romania",
        "russia", "rwanda", "samoa", "scotland", "senegal", "serbia",
        "seychelles", "singapore", "slovakia", "slovenia", "somalia", "spain",
        "sudan", "suriname", "swaziland", "sweden", "switzerland", "syria",
        "taiwan", "tajikistan", "tanzania", "thailand", "togo", "tonga",
        "tunisia", "turkey", "turkmenistan", "tuvalu", "uganda", "ukraine",
        "uruguay", "uzbekistan", "vanuatu", "venezuela", "vietnam", "wales",
        "yemen", "zambia", "zimbabwe",
    ],
    "arctic_animals": [
        "polar", "bear", "walrus", "seal", "narwhal", "beluga", "orca", "whale",
        "moose", "caribou", "reindeer", "musk", "ox", "fox", "wolf", "wolverine",
        "lemming", "hare", "ermine", "weasel", "stoat", "marten", "lynx",
        "puffin", "auk", "guillemot", "tern", "ptarmigan", "snowy", "owl",
        "eider", "snow", "goose", "skua", "fulmar", "kittiwake", "murre",
        "jaeger", "gyrfalcon", "raven", "albatross", "petrel", "krill",
        "salmon", "cod", "halibut", "sturgeon", "char", "trout", "herring",
        "capelin", "narwhal", "bowhead", "minke", "humpback", "fin", "blue",
        "whale", "leopard", "elephant", "weddell", "ross", "crabeater",
        "fur", "harbor", "ringed", "bearded", "harp", "hooded", "northern",
    ],
    "zoo_animals": [
        "lion", "tiger", "leopard", "jaguar", "cheetah", "panther", "puma",
        "cougar", "lynx", "ocelot", "serval", "caracal", "elephant", "rhino",
        "rhinoceros", "hippo", "hippopotamus", "giraffe", "okapi", "zebra",
        "wildebeest", "gnu", "buffalo", "bison", "ox", "yak", "camel",
        "dromedary", "llama", "alpaca", "vicuna", "guanaco", "antelope",
        "gazelle", "impala", "kudu", "eland", "gemsbok", "oryx", "springbok",
        "ibex", "chamois", "moose", "elk", "deer", "reindeer", "caribou",
        "kangaroo", "wallaby", "koala", "wombat", "platypus", "echidna",
        "tasmanian", "devil", "opossum", "possum", "sloth", "armadillo",
        "anteater", "aardvark", "pangolin", "porcupine", "hedgehog", "shrew",
        "mole", "bat", "monkey", "ape", "gorilla", "chimp", "chimpanzee",
        "orangutan", "gibbon", "baboon", "macaque", "lemur", "marmoset",
        "tamarin", "capuchin", "spider", "howler", "squirrel", "loris",
        "tarsier", "bear", "polar", "grizzly", "panda", "sloth", "sun",
        "spectacled", "wolf", "fox", "coyote", "jackal", "dingo", "hyena",
        "meerkat", "mongoose", "civet", "raccoon", "skunk", "otter", "beaver",
        "muskrat", "capybara", "porcupine", "hedgehog", "rabbit", "hare",
        "ostrich", "emu", "cassowary", "rhea", "kiwi", "peacock", "flamingo",
        "pelican", "stork", "crane", "ibis", "heron", "egret", "spoonbill",
        "vulture", "eagle", "hawk", "falcon", "owl", "parrot", "macaw",
        "toucan", "hornbill", "kookaburra", "snake", "python", "boa", "cobra",
        "viper", "rattlesnake", "anaconda", "lizard", "iguana", "monitor",
        "gecko", "chameleon", "tortoise", "turtle", "crocodile", "alligator",
        "caiman", "gharial",
    ],
    "herb": [
        "basil", "oregano", "thyme", "rosemary", "sage", "parsley", "cilantro",
        "coriander", "mint", "spearmint", "peppermint", "chive", "chives",
        "dill", "fennel", "tarragon", "marjoram", "savory", "lemongrass",
        "lavender", "chamomile", "echinacea", "valerian", "verbena", "sorrel",
        "chervil", "borage", "bay", "laurel", "anise", "lovage", "rue",
        "hyssop", "comfrey", "nettle", "feverfew", "horehound", "mugwort",
        "wormwood", "yarrow", "angelica", "burnet", "calendula", "catnip",
        "elderflower", "ginseng", "goldenseal", "hawthorn", "lemonbalm",
        "marshmallow", "milkthistle", "motherwort", "oregon", "passionflower",
        "raspberry", "rose", "rosehip", "saint", "skullcap", "stinging",
        "tansy", "valerian", "violet", "willow", "witch", "hazel", "wormwood",
    ],
    "musical_instrument": [
        "piano", "keyboard", "organ", "harpsichord", "synthesizer", "synth",
        "accordion", "harmonica", "melodica", "guitar", "bass", "ukulele",
        "banjo", "mandolin", "lute", "harp", "lyre", "zither", "sitar",
        "violin", "viola", "cello", "fiddle", "contrabass", "doublebass",
        "drums", "drum", "snare", "bass", "tom", "cymbal", "hihat", "ride",
        "crash", "tambourine", "triangle", "cowbell", "maracas", "claves",
        "bongo", "bongos", "conga", "congas", "djembe", "tabla", "timpani",
        "xylophone", "marimba", "vibraphone", "glockenspiel", "chimes",
        "bell", "bells", "gong", "trumpet", "cornet", "bugle", "trombone",
        "tuba", "euphonium", "horn", "frenchhorn", "saxophone", "alto",
        "tenor", "soprano", "baritone", "clarinet", "oboe", "bassoon",
        "flute", "piccolo", "fife", "recorder", "bagpipe", "bagpipes",
        "didgeridoo", "kazoo", "ocarina", "panpipe", "pipe", "whistle",
        "shaker", "rattle", "castanets", "woodblock", "anvil",
    ],
    "cleaning_supply": [
        "soap", "detergent", "bleach", "ammonia", "vinegar", "scrubber",
        "scrub", "sponge", "rag", "cloth", "towel", "duster", "broom",
        "mop", "bucket", "pail", "vacuum", "hoover", "swiffer", "feather",
        "squeegee", "brush", "toothbrush", "scouring", "pad", "polish",
        "wax", "spray", "cleaner", "disinfectant", "sanitizer", "wipe",
        "wipes", "tissue", "paper", "napkin", "trash", "garbage", "bag",
        "bin", "can", "compost", "recycle", "gloves", "apron", "mask",
        "shovel", "dustpan", "broom", "feather", "lint", "roller", "iron",
        "ironing", "board", "starch", "fabric", "softener", "dryer", "sheet",
        "bleach", "laundry", "soda", "borax", "baking", "scrubber",
    ],
    "car_part": [
        "engine", "motor", "transmission", "gearbox", "clutch", "axle",
        "drivetrain", "differential", "driveshaft", "exhaust", "muffler",
        "tailpipe", "catalytic", "converter", "manifold", "radiator",
        "alternator", "starter", "battery", "spark", "plug", "coil",
        "cylinder", "piston", "crankshaft", "camshaft", "valve", "carburetor",
        "fuel", "injector", "tank", "filter", "oil", "pump", "belt", "hose",
        "tire", "wheel", "rim", "hubcap", "lugnut", "brake", "pad", "rotor",
        "caliper", "drum", "shoe", "strut", "shock", "absorber", "spring",
        "suspension", "control", "arm", "tie", "rod", "rack", "pinion",
        "steering", "wheel", "column", "horn", "dashboard", "console",
        "speedometer", "odometer", "tachometer", "gauge", "indicator",
        "headlight", "headlamp", "taillight", "blinker", "signal", "fog",
        "lamp", "bumper", "fender", "hood", "trunk", "boot", "bonnet",
        "door", "window", "windshield", "wiper", "mirror", "antenna",
        "grille", "panel", "seat", "belt", "buckle", "airbag", "pedal",
        "gas", "throttle", "key", "ignition", "lock", "handle",
    ],
    "car_brand": [
        "ford", "chevrolet", "chevy", "dodge", "chrysler", "jeep", "ram",
        "buick", "cadillac", "lincoln", "tesla", "rivian", "gmc", "pontiac",
        "saturn", "oldsmobile", "mercury", "plymouth", "hummer", "toyota",
        "lexus", "honda", "acura", "nissan", "infiniti", "mazda", "subaru",
        "mitsubishi", "suzuki", "isuzu", "datsun", "hyundai", "kia", "genesis",
        "daewoo", "ssangyong", "volkswagen", "audi", "porsche", "bmw",
        "mercedes", "benz", "smart", "opel", "skoda", "seat", "renault",
        "peugeot", "citroen", "fiat", "alfa", "romeo", "lancia", "ferrari",
        "lamborghini", "maserati", "bugatti", "pagani", "mclaren", "lotus",
        "aston", "martin", "bentley", "jaguar", "land", "rover", "rolls",
        "royce", "mini", "mg", "morris", "vauxhall", "volvo", "saab", "koenigsegg",
        "polestar", "byd", "geely",
    ],
    "insect": [
        "ant", "bee", "wasp", "hornet", "yellowjacket", "bumblebee", "honeybee",
        "fly", "housefly", "horsefly", "fruitfly", "blowfly", "dragonfly",
        "damselfly", "mayfly", "firefly", "butterfly", "moth", "caterpillar",
        "beetle", "ladybug", "ladybird", "weevil", "stagbeetle", "scarab",
        "june", "bug", "june", "stinkbug", "boxelder", "leafhopper",
        "grasshopper", "cricket", "katydid", "locust", "cicada", "aphid",
        "thrip", "mealybug", "scale", "whitefly", "earwig", "cockroach",
        "roach", "termite", "silverfish", "louse", "lice", "flea", "tick",
        "mite", "chigger", "mosquito", "midge", "gnat", "punkie", "noseeum",
        "mantis", "stickbug", "walkingstick", "leafbug", "treehopper",
        "planthopper", "spittlebug", "lacewing", "antlion", "doodlebug",
        "spider", "tarantula", "scorpion", "centipede", "millipede",
    ],
}


def main() -> None:
    with DICT_PATH.open() as f:
        words = {w.strip().lower() for w in f if w.strip().isalpha()}
    print(f"Loaded dictionary: {len(words):,} words")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    with (DATA / "categories.json").open() as f:
        categories = json.load(f)

    seeded_ids = set(SEEDS.keys())
    declared_ids = {c["id"] for c in categories}
    missing = declared_ids - seeded_ids
    extra = seeded_ids - declared_ids
    if missing:
        print(f"WARNING: missing seeds for: {sorted(missing)}")
    if extra:
        print(f"WARNING: seeds for unknown categories: {sorted(extra)}")

    total_out = 0
    for cat_id, seeds in SEEDS.items():
        accepted: list[str] = []
        seen: set[str] = set()
        for w in seeds:
            wl = w.strip().lower()
            if not wl or not wl.isalpha() or wl in seen:
                continue
            if wl in words:
                seen.add(wl)
                accepted.append(wl.upper())
        out_path = OUT_DIR / f"{cat_id}.txt"
        out_path.write_text("\n".join(accepted) + "\n")
        total_out += len(accepted)
        print(f"  {cat_id:25s} {len(accepted):4d} words")

    print(f"\nTotal words across all categories: {total_out:,}")
    print(f"Wrote {len(SEEDS)} category files to {OUT_DIR}")


if __name__ == "__main__":
    main()
